@startuml
actor Client
actor Driver

usecase Server
usecase ClientApp
usecase DriverApp
usecase IClientNotifier

Client --> ClientApp : "run app"
ClientApp -up-> Client
Driver -> DriverApp : "run app"
DriverApp -> Driver

usecase ClientOrderCommandHandler
usecase TripService
usecase IDriverFounder
usecase IDriverNotifier
usecase DriverCommandHandler

ClientApp -left-> ClientOrderCommandHandler : "send approve"
ClientOrderCommandHandler -down-> TripService : "start trip request"
TripService -> IDriverFounder : "find driver"
IDriverFounder -> IDriverNotifier : "notify nearest drivers"
IDriverNotifier -> DriverApp : "show trip request"
DriverApp -down-> DriverCommandHandler : "send confirmation"
DriverCommandHandler -left-> TripService : "starting trip"
TripService -up-> IClientNotifier : "notify trip started"
IClientNotifier -up-> ClientApp : "notify driver found"


 

@enduml